services:
  mongo-prod:
    image: mongo:6
    networks:
      - app-network
    restart: unless-stopped

  backend-prod:
    image: ${DOCKERHUB_NAMESPACE:-maharshi86}/react-node-ci-backend:${IMAGE_TAG}
    env_file:
      - ./.env.prod
    ports:
      - "5001:5000"
    depends_on:
      - mongo-prod
    networks:
      - app-network
    restart: unless-stopped

  frontend-prod:
    image: ${DOCKERHUB_NAMESPACE:-maharshi86}/react-node-ci-frontend:${IMAGE_TAG}
    depends_on:
      - backend-prod
    networks:
      - app-network
    restart: unless-stopped

  nginx-prod:
    image: ${DOCKERHUB_NAMESPACE:-maharshi86}/react-node-ci-nginx:${IMAGE_TAG}
    ports:
      - "80:80"
    depends_on:
      - frontend-prod
      - backend-prod
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
