server {
  listen 80;

  # =========================
  # 🔥 PRODUCTION
  # =========================

  location / {
    proxy_pass http://app-frontend-prod:80;
  }

  location /api/ {
    proxy_pass http://app-backend-prod:8001/;
  }

  # =========================
  # 🧪 DEVELOPMENT
  # =========================

  location /dev/ {
    rewrite ^/dev/(.*)$ /$1 break;
    proxy_pass http://app-frontend-dev:80;
  }

  location /dev/api/ {
    rewrite ^/dev/api/(.*)$ /$1 break;
    proxy_pass http://app-backend-dev:8001/;
  }
}
